### ISSUE TITLE
Acabar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s3-evaluacion-intermedia-oljuanfe#1]
Te dejo algunas pistas para que puedas mejorarlo:

- Iterar en App el array de pokemons con un map, y en cada iteración pintar el elemento `PokemonLi` pasandole las propiedades de ese item en lugar de todo el array `<PokemonLi name={poekmon.name}... /> `
- Iterar en `PokemonLi` el array de types para pintarlos.
- Mejorar la indentación.
- No descuidar la semántica de HTML (main, h1...)
- Añadir keys en los listados (https://reactjs.org/docs/lists-and-keys.html)
- Animarte a hacer destructuring para no escribir tantas veces `this.props`
- Instalar la librería `prop-types` y usarla para comprobar el tipado js de las props.
- Acabar el css
- Eliminar archivos que no usamos (App.test.js, logo.svg...)

También te recomiendo publicar en Github Pages para practicar ;)

A por ello!

**Comment by oljuanfe** [comment]
Creo que ya esta completo. Cuando puedas me comentas, por favor. Gracias!

**Comment by nasivuela** [comment]
@oljuanfe Buen trabajo!!!!

Una vez que instalas proptypes, puedes usarla en todos tus componentes ;)
